config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index,:show,:new,:create,:edit,:update]

  resources :cat_rental_requests, only: [:new,:create] do
    patch :approve, on: :member
    patch :deny, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  description :text             not null
#  name        :string           not null
#  sex         :string(1)        not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

require 'action_view'

class Cat < ApplicationRecord

    include ActionView::Helpers::DateHelper

    COLORS = %w(orange black white grey black/white grey/white orange/white black/grey)

    validates :birth_date,:color,:description,:name,:sex,presence:true
    validates :sex,inclusion: ['f','m']
    validates :color,inclusion: [*COLORS]

    def age
        #Time.now.year - birth_date.year
        #-c.birth_date.years_ago(Time.now.year).year
        time_ago_in_words((Time.now.year - birth_date.year).years.ago)
    end

    has_many :cat_rental_requests,
        dependent: :destroy

    has_many :ordered_cat_rental_requests,
        ->(request){order(:start_date)},
        class_name: :CatRentalRequest
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  end_date   :date             not null
#  start_date :date             not null
#  status     :string           default("PENDING"), not null
#  cat_id     :integer          not null
#
# Indexes
#
#  index_cat_rental_requests_on_cat_id  (cat_id)
#
class CatRentalRequest < ApplicationRecord
    validates :status,:start_date,:end_date,presence: true
    validates :status,inclusion: ['APPROVED','DENIED','PENDING']
    validate :does_not_overlap_approved_request

    belongs_to :cat  

    def approve!
        CatRentalRequest.transaction do
            self.status = 'APPROVED'
            save 
            overlapping_pending_requests.each do |request| 
                request.status = 'DENIED'
                request.save
            end
        end 
    end

     def deny!
       CatRentalRequest.transaction do
            self.status = 'DENIED'
            save
       end
    end

    def overlapping_requests
        # CatRentalRequest.
        # where(cat_id: cat_id).
        # where(start_date: start_date..end_date).
        # where.not(id: id).
        # or(CatRentalRequest.
        # where(cat_id: cat_id).
        # where(end_date: start_date..end_date).
        # where.not(id: id)).
        # or(CatRentalRequest.
        # where(cat_id: cat_id).
        # where('cat_rental_requests.start_date < ? AND cat_rental_requests.end_date > ?',start_date,end_date).
        # where.not(id: id))  

        CatRentalRequest.
        where(cat_id: cat_id).
        where.not(id:id).
        where.not("cat_rental_requests.start_date > ? OR cat_rental_requests.end_date < ?",end_date,start_date)
    end

    def overlapping_pending_requests
        overlapping_requests.where(status:'PENDING')
    end

    def overlapping_approved_requests
        overlapping_requests.where(status:'APPROVED')
    end

    def does_not_overlap_approved_request
        if ((self.persisted? && (self.status == 'APPROVED' || self.status== 'PENDING')) || (!self.persisted?))  && overlapping_approved_requests.exists?
            errors.add(:base,"Request overlaps with another that is already approved")  
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

    def new
        @request = CatRentalRequest.new
        render :new
    end

    def create
        @request = CatRentalRequest.new(request_params)
        if @request.save
            redirect_to cat_url(@request.cat_id)
        else  
            render :new
        end
    end

    def approve
        request = CatRentalRequest.find_by(id:params[:id])
        request.approve!
        redirect_to cat_url(request.cat_id)
    end

    def deny
        request = CatRentalRequest.find_by(id:params[:id])
        request.deny!
        redirect_to cat_url(request.cat_id)
    end

    private

    def request_params
        params.require(:cat_rental_request).permit(:cat_id,:start_date,:end_date)
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all 
        render :index
    end

    def show
        @c = Cat.find_by(id: params[:id])
        render :show
    end

    def new
        @c = Cat.new
        render :new
    end

    def create
        @c = Cat.new(cat_params)
        if @c.save
            redirect_to cat_url(@c)
        else
            render :new
        end
    end

    def edit
        @c = Cat.find_by(id: params[:id])
        render :edit
    end

    def update
        @c = Cat.find_by(id: params[:id])
        if @c.update(cat_params)
            redirect_to cat_url(@c)
        else  
            render :edit 
        end
    end

    private

    def cat_params
        params.require(:cat).permit(:name,:birth_date,:sex,:color,:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<h1><%= link_to '99 Cats', cats_url %></h1>

<h1>Make a request to rent a cat</h1>

<form action= <%= cat_rental_requests_url %> method="POST">
    <div>
        <label style="display:block;" for="cat">Cat</label>
        <select name="cat_rental_request[cat_id]" id="cat">
            <option disabled selected>--Please select a cat--</option>
            <% Cat.all.each do |cat| %>
                <option value= <%= cat.id %>><%= cat.name %></option>
            <% end %>
        </select>
    </div>

    <br>

    <div>
        <label  style="display:block;" for="start_date">Start Date</label>
        <input id="start_date" type="date" name= "cat_rental_request[start_date]">
    </div>

    <br>

    <div>
        <label style="display:block;" for="end_date">End Date</label>
        <input id="end_date" type="date" name= "cat_rental_request[end_date]">
    </div>

    <br>
    <br>

    <input type="submit" value="Submit request">
    
</form>

app/views/cats/_form.html.erb
<% action_url = action == :new ? cats_url : cat_url(c) %>

<form action= <%= action_url %> method="POST">
    <% if action == :edit %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>
    <div>
        <label for="name">Name</label>
        <input type="text" id="name" name="cat[name]" value=  <%= c ? c.name : ""%>>
    </div>

    <br>

    <div>
        <label for="birth_date">Birth_date</label>
        <input type="date" id="birth_date" name="cat[birth_date]" value=  <%= c ? c.birth_date : ""%>>
    </div>
    
    <br>

    <div>
        <label for="male">Male</label>
        <input type="radio" id="male" name="cat[sex]" value="m" <%= 'checked' if c && c.sex == 'm' %>>
    
        <label for="female">Female</label>
        <input type="radio" id="female" name="cat[sex]" value="f" <%= 'checked' if c && c.sex == 'f' %>>     
    </div>

    <br>

    <div>
        <label for="color">Color</label>
        <select name="cat[color]" id="color">
            <option selected disabled>--Select a color--</option>
            <% Cat::COLORS.each do |color| %>
            <option value= <%= color %> <%= 'selected' if c && c.color == color %>><%= color.capitalize %></option>
            <% end %>
        </select>
    </div>

    <br>

    <div>
        <textarea name="cat[description]" id="description" cols="30" rows="10"><%=
           c.description if c && c.description
        %></textarea>
    </div>

    <br>
    <br>

    <input type="submit" value="Submit" >
</form>

app/views/cats/edit.html.erb
<h1><%= link_to '99 Cats', cats_url %></h1>

<h2>Edit the info of a cat </h1>

<%= render 'form',action: :edit,c: @c %>

app/views/cats/index.html.erb
<h1><%= link_to '99 Cats', cats_url %></h1>

<ul>
    <% @cats.each do |cat| %>
        <li><%= link_to cat.name, cat_url(cat) %></li>
    <% end %>
</ul>

<br>
<br>

<p><%= link_to 'Add a new cat', new_cat_url %></p>

<p><%= link_to 'Rent a cat', new_cat_rental_request_url %></p>

app/views/cats/new.html.erb
<h1><%= link_to '99 Cats', cats_url %></h1>

<h2>Enter the info of the admitted cat </h1>

<%= render 'form',action: :new,c: @c %>

app/views/cats/show.html.erb
<h1><%= link_to '99 Cats', cats_url %></h1>

<h1><%= @c.name %></h1> 

<table border="1" width="300px">
    <caption><%= @c.name %>'s Details</caption>
    <tr>
        <th>Age</th>
        <td><%= @c.age %></td>
    </tr>
    <tr>
        <th>Gender</th>
        <td><%= @c.sex == 'm' ? 'Male' : 'Female' %></td>
    </tr>
    <tr>
        <th>Color</th>
        <td><%= @c.color.capitalize %></td>
    </tr>
    <tr>
        <th>Description</th>
        <td><%= @c.description %></td>
    </tr>
</table>

<p><%= link_to "Edit #{@c.name}\'s details", edit_cat_url(@c) %></p>

<% unless @c.ordered_cat_rental_requests.empty? %>
    <table border="1px">
        <caption>Submitted requests</caption>
        <thead>
            <tr>
                <th>From</th>
                <th>To</th>
                <th>Status</th>
                <% if @c.cat_rental_requests.where(status: 'PENDING').exists? %>
                    <th span="2" align-text="center">Approval</th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @c.ordered_cat_rental_requests.each do |request| %>
                <tr>
                    <td> <%= request.start_date %> </td>
                    <td> <%= request.end_date   %> </td>
                    <td> <%= request.status %>     </td>
                    <% if request.status == 'PENDING' %>
                        <td> <%= button_to 'Approve', approve_cat_rental_request_url(request.id),method: :patch %></td>
                        <td> <%= button_to 'Deny', deny_cat_rental_request_url(request.id), method: :patch %></td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>